version: "3.7"

services:
  proxy:
    container_name: rt-proxy
    image: nginx:mainline-alpine3.18-slim
    ports:
      - ${PORT:-3589}:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=${TIMEZONE:-America/Chicago}
    networks:
      - internal
    depends_on:
      - php
      - mariadb

  php:
    container_name: rt-php
    build: './docker/php'
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - TZ=${TIMEZONE:-America/Chicago}
    networks:
      - internal
    depends_on:
      - mariadb

  phpmyadmin:
    container_name: rt-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=rt-mariadb
      - TZ=${TIMEZONE:-America/Chicago}
    networks:
      - internal
    depends_on:
      - mariadb

  mariadb:
    container_name: rt-mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - rt-mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=DevelopmentPassword
      - TZ=${TIMEZONE:-America/Chicago}
    networks:
      - internal

volumes:
  rt-mariadb-data:


networks:
  internal:
    driver: bridge
