CREATE OR REPLACE DATABASE calendar_track;

USE calendar_track;

-- calendar
CREATE TABLE `calendar` (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	ics_link MEDIUMTEXT NOT NULL,
	enable_weather BOOLEAN NOT NULL DEFAULT false,
	active BOOLEAN NOT NULL DEFAULT true
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
